[project]
name = "capsim-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jesse Sawyers", email = "sawyers.jesse@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
capsim-analyzer = "capsim_analyzer:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
